AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 35

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 60

Metrics/ModuleLength:
  Max: 250

Metrics/PerceivedComplexity:
  Max: 12

Style/StringLiterals:
  EnforcedStyle: double_quotes
